<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>@yield('title')</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            font-size: 10px;
            color: #334155;
            line-height: 1.5;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 10px;
        }
        .company-name {
            font-size: 18px;
            font-weight: bold;
            color: #1e293b;
            text-transform: uppercase;
        }
        .report-title {
            font-size: 14px;
            font-weight: bold;
            color: #64748b;
            margin-top: 5px;
        }
        .meta {
            margin-bottom: 20px;
            width: 100%;
        }
        .meta td {
            padding: 2px 0;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .table th {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            padding: 8px;
            text-align: left;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 8px;
            color: #64748b;
        }
        .table td {
            border: 1px solid #e2e8f0;
            padding: 8px;
            vertical-align: top;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 5px;
        }
        .summary-box {
            background-color: #f1f5f9;
            padding: 10px;
            border-radius: 4px;
            margin-bottom: 20px;
        }
        .summary-title {
            font-weight: bold;
            margin-bottom: 5px;
            text-transform: uppercase;
            font-size: 9px;
            color: #475569;
        }
        .summary-grid {
            width: 100%;
        }
        .summary-item {
            padding: 5px;
        }
        .label {
            font-weight: bold;
            color: #64748b;
        }
        .value {
            color: #1e293b;
            font-weight: bold;
        }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .bg-emerald { color: #059669; }
        .bg-rose { color: #e11d48; }
        .bg-sky { color: #0284c7; }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">{{ $settings['company_name'] ?? config('app.name') }}</div>
        <div class="report-title">@yield('report_title')</div>
    </div>

    <div class="meta">
        <table style="width: 100%">
            <tr>
                <td style="width: 50%">
                    <strong>Period:</strong> {{ $startDate ?? '-' }} to {{ $endDate ?? '-' }}
                </td>
                <td style="width: 50%; text-align: right;">
                    <strong>Generated On:</strong> {{ now()->format('d M Y H:i') }}
                </td>
            </tr>
        </table>
    </div>

    @yield('content')

    <div class="footer">
        Generated by {{ config('app.name') }} | Page <span class="pagenum"></span>
    </div>
</body>
</html>
